/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "bg-colors-white": "#fff",
        black: "#000",
        "colors-slate-300": "#cbd5e1",
        "text-colors-gray": "#404040",
        "colors-slate-50": "#f8fafc",
        "text-colors-dark-gray": "#111827",
        "text-colors-amber": "#f59e0b",
        "button-colors-dark-sky": "#0369a1",
        royalblue: "#094db2",
        "colors-slate-950": "#020617",
        "colors-slate-500": "#64748b",
        "bg-colors-light-gray": "#fafafa",
        gray: "#676f82",
        "dark-gray": "#334158",
        "colors-blue-50": "#eff6ff",
        "colors-blue-100": "#dbeafe",
        "colors-blue-200": "#bfdbfe",
        "colors-green-50": "#f0fdf4",
        "colors-green-100": "#dcfce7",
        "colors-green-400": "#4ade80",
        "colors-green-300": "#86efac",
        "colors-green-200": "#bbf7d0",
        "colors-red-50": "#fef2f2",
        "colors-red-100": "#fee2e2",
        "colors-red-200": "#fecaca",
        "text-colors-normal": "#030712",
        "colors-indigo-300": "#a5b4fc",
        "colors-blue-300": "#93c5fd",
        "colors-red-300": "#fca5a5",
        "colors-gray-300": "#d1d5db",
        "colors-cyan-950": "#083344",
        "bg-light-border": "#e4e4e7",
        "text-light-gray": "#a3a3a3",
        "text-dark-gray": "#334155",
        "bg-light": "#fafaf9",
        "text-title-small-light": "#52525b",
        "colors-neutral-300": "#d4d4d4",
        "text-gray": "#6b7280",
        "light-border": "#e2e4ea",
        "text-title-large": "#475569",
        "text-text-small": "#0f172a",
        gainsboro: "#e7e7e7",
        "colors-cyan-800": "#155e75",
        "semantic-success": "#22c55e",
      },
      spacing: {
        "spacing-2": "8px",
        "spacing-5": "20px",
        "spacing-4": "16px",
        "spacing-0-5": "2px",
        "spacing-2-5": "10px",
        "spacing-7": "28px",
        "spacing-1": "4px",
      },
      fontFamily: {
        "headings-headling-2": "NanumGothic",
        "body-text-small-text-semibold": "'Noto Sans KR'",
        "sub-sub-item": "'Nanum Gothic'",
        "text-small": "Inter",
      },
      borderRadius: {
        xl: "20px",
        "10xs": "3px",
        "21xl": "40px",
        "default-border-raius": "4px",
        "default-border-raius1": "4px",
      },
    },
    fontSize: {
      "17xl": "2.25rem",
      sm: "0.875rem",
      base: "1rem",
      "29xl": "3rem",
      lg: "1.125rem",
      xs: "0.75rem",
      smi: "0.813rem",
      "5xl": "1.5rem",
      "11xl": "1.875rem",
      "2xs": "0.688rem",
      "7xl": "1.625rem",
      inherit: "inherit",
    },
    screens: {
      md: {
        max: "960px",
      },
      sm: {
        max: "640px",
      },
      mq420: {
        raw: "screen and (max-width: 420px)",
      },
    },
  },
  corePlugins: {
    preflight: false,
  },
};
